#!/usr/bin/perl -cw
#
# You should check the syntax of this file before using it in an auto-install.
# You can do this with 'perl -cw auto_inst.cfg.pl' or by executing this file
# (note the '#!/usr/bin/perl -cw' on the first line).
$o = {
       'X' => {
	      },
       'authentication' => {
			     'sha512' => 1,
			     'shadow' => 1
			   },
       'autoExitInstall' => '1',
       'default_packages' => [
			       'acpi',
			       'acpid',
			       'akregator',
			       'alsa-utils',
			       'aoss',
			       'aria2',
			       'basesystem',
			       'bash-completion',
			       'bc',
			       'bind-utils',
			       'bluez-firmware',
			       'cdrkit-genisoimage',
			       'clementine',
			       'comgt',
			       'coreutils-doc',
			       'cpupower',
			       'cronie-anacron',
			       'dconf',
			       'dcraw',
			       'dhcp-client',
			       'digikam',
			       'dmraid',
			       'dnf',
			       'dnf-plugins-core',
			       'drakconf',
			       'drakguard',
			       'dump',
			       'dvdauthor',
			       'efax',
			       'ekiga',
			       'enscript',
			       'ffmpegthumbs',
			       'filezilla',
			       'firefox-en_GB',
			       'firefox-en_US',
			       'firefox-en_ZA',
			       'fonts-ttf-decoratives',
			       'fonts-ttf-west_european',
			       'ghostscript-module-X',
			       'giftrans',
			       'gnome-packagekit-common',
			       'gnupg',
			       'gphoto2',
			       'gpm',
			       'grub-doc',
			       'grub2-mageia-theme',
			       'gstreamer0.10-pulse',
			       'gstreamer1.0-a52dec',
			       'gstreamer1.0-cdparanoia',
			       'gstreamer1.0-flac',
			       'gstreamer1.0-plugins-good',
			       'gstreamer1.0-plugins-ugly',
			       'gstreamer1.0-pulse',
			       'gstreamer1.0-soup',
			       'harddrake',
			       'hdparm',
			       'hexedit',
			       'hunspell',
			       'icewm-i18n',
			       'icewm-light',
			       'imagemagick',
			       'info',
			       'irqbalance',
			       'iwlwifi-agn-ucode',
			       'kaddressbook',
			       'kalarm',
			       'kcharselect',
			       'kcolorchooser',
			       'kcron',
			       'kde-l10n-en_GB',
			       'kde-l10n-en_US',
			       'kdegraphics-mobipocket',
			       'kdegraphics-thumbnailers',
			       'kdenlive',
			       'kernel-desktop-latest',
			       'kernel-firmware-nonfree',
			       'kfilemetadata',
			       'kgamma5',
			       'khtml',
			       'kipi-plugins-facebook',
			       'kipi-plugins-flashexport',
			       'kipi-plugins-flickr',
			       'kipi-plugins-kmlexport',
			       'kipi-plugins-printimages',
			       'kipi-plugins-rajceexport',
			       'kipi-plugins-sendimages',
			       'kipi-plugins-smug',
			       'kipi-plugins-vkontakte',
			       'kipi-plugins-yandexfotki',
			       'kjots',
			       'kleopatra',
			       'kmail',
			       'kmozillahelper',
			       'knotes',
			       'kolourpaint',
			       'konq-plugins',
			       'kontact',
			       'konversation',
			       'korganizer',
			       'ktimer',
			       'ktorrent',
			       'kwallet-pam',
			       'ladspa',
			       'ldetect',
			       'lftp',
			       'lib64alsa-plugins',
			       'lib64glib-networking',
			       'lib64javascriptcore-gir4.0',
			       'lib64kbookmarkmodel_private_5',
			       'lib64phonon4qt5experimental4',
			       'libggi',
			       'libofx',
			       'libplist',
			       'libpwquality-tools',
			       'libreoffice-base',
			       'libreoffice-draw',
			       'libreoffice-impress',
			       'libreoffice-langpack-en',
			       'libreoffice-math',
			       'libreoffice-writer',
			       'libreoffice-xsltfilter',
			       'lsof',
			       'lvm2',
			       'lynx',
			       'mageia-gfxboot-theme',
			       'mageiawelcome',
			       'man-pages',
			       'mandi-ifw',
			       'mc',
			       'mencoder',
			       'mgaonline',
			       'microcode',
			       'microcode_ctl',
			       'mirrordir',
			       'mjpegtools',
			       'mkxauth',
			       'mlocate',
			       'mpgtx',
			       'msec-gui',
			       'mtools',
			       'nano',
			       'net_monitor',
			       'netprofile-plugin-network',
			       'notification-daemon',
			       'npapi-vlc',
			       'numlock',
			       'okular',
			       'open',
			       'openssh-clients',
			       'os-prober',
			       'p7zip',
			       'packagekit-gstreamer-plugin',
			       'patch',
			       'pavucontrol',
			       'perl-Hal-Cdroms',
			       'perl-Time-HiRes',
			       'poppler-data',
			       'preload',
			       'procmail',
			       'psutils',
			       'radeon-firmware',
			       'ralink-firmware',
			       'rdist',
			       'recode',
			       'rfkill',
			       'rsync',
			       'rtlwifi-firmware',
			       's2u',
			       'screen',
			       'sharutils',
			       'shorewall-ipv6',
			       'skrooge',
			       'soundwrapper',
			       'spectacle',
			       'strace',
			       'sudo',
			       'symlinks',
			       'system-config-printer',
			       'task-codec-audio',
			       'task-codec-video',
			       'task-plasma5-minimal',
			       'task-pulseaudio',
			       'telepathy-idle',
			       'telepathy-kde-desktop-applets',
			       'tmpwatch',
			       'tree',
			       'ufraw-gimp',
			       'usbutils',
			       'vaapi-driver-intel',
			       'vboxadditions-kernel-desktop-latest',
			       'vim-minimal',
			       'virtualbox-guest-additions',
			       'vlc-plugin-flac',
			       'vlc-plugin-pulse',
			       'vlc-plugin-speex',
			       'vlc-plugin-theora',
			       'vorbis-tools',
			       'vte3',
			       'wget',
			       'wireless-tools',
			       'words',
			       'x11-driver-input',
			       'x11-driver-video',
			       'xdm',
			       'xorg-x11-75dpi-fonts',
			       'yelp',
			       'zeroconf-ioslave',
			       'zip',

             'openssh-server',
			     ],
       'enabled_media' => [
			    'Core Release'
			  ],
       'keyboard' => {
		       'GRP_TOGGLE' => '',
		       'KEYBOARD' => 'us'
		     },
       'locale' => {
		     'IM' => undef,
		     'country' => 'US',
		     'lang' => 'en_US',
		     'langs' => {
				  'en_US' => 1
				},
		     'utf8' => 1
		   },
       'net' => {
		  'PROFILE' => 'default',
		  'ethernet' => {},
		  'ifcfg' => {
			       'enp0s3' => {
					     'BOOTPROTO' => 'dhcp',
					     'BROADCAST' => '',
					     'DEVICE' => 'enp0s3',
					     'HWADDR' => undef,
					     'METRIC' => 10,
					     'NETMASK' => '255.255.255.0',
					     'NETWORK' => '',
					     'ONBOOT' => 'yes'
					   }
			     },
		  'net_interface' => 'enp0s3',
		  'network' => {
				 'CRDA_DOMAIN' => 'US',
				 'NETWORKING' => 'yes'
			       },
		  'resolv' => {
				'DOMAINNAME' => undef,
				'DOMAINNAME2' => undef,
				'DOMAINNAME3' => undef,
				'dnsServer' => undef,
				'dnsServer2' => undef,
				'dnsServer3' => undef
			      },
		  'type' => 'ethernet',
		  'wireless' => {},
		  'zeroconf' => {}
		},
       'partitioning' => {
			   'auto_allocate' => '1',
			   'clearall' => 1
			 },
       'security' => 1,
       'security_user' => undef,
       'superuser' => {
			'gid' => '0',
			'home' => '/root',
			'password' => 'vagrant',
			'realname' => 'root',
			'shell' => '/bin/bash',
			'uid' => '0'
		      },
       'timezone' => {
		       'UTC' => 1,
		       'ntp' => undef,
		       'timezone' => 'UTC'
		     },
       'users' => [
		    {
		      'gid' => undef,
		      'groups' => [
				    'wheel'
				  ],
          'password' => 'vagrant',
		      'icon' => 'default',
		      'name' => 'vagrant',
		      'realname' => undef,
		      'shell' => '/bin/bash',
		      'uid' => undef
		    }
		  ]
     };
